RAG integration
aimclub/ProtoLLM pull request #8
Opened 2024-12-10 12:42 UTC by vanoha

Implemented RAG pipeline:

* main RAG pipeline with reranking (2 ways: use only retrieving based on chunk content; use retrieving based on chunk content and keywords, extracted from chunk)
* loaders to chroma and elastic DB
* etl pipeline (inlcuding parsers of different file extensions and splitting based on different strategies)

2024-12-15 22:11 UTC, nicl-nno commented on protollm/docs_processing/parsing/parsers/utilities.py
> +TITLE_KEYWORDS = ['альметьевск', 'казань']
Вот это кажется нужно убрать.

Ну и в целом ключевые слова явно на какой-то определенный тип документов нацелен - будет полезно это в названии файла или комментариях указать.

2024-12-15 22:22 UTC, nicl-nno commented on protollm/rags/configs/chroma.env
> +ALLOW_RESET=False
Локальные адреса лучше убрать.

2024-12-15 22:24 UTC, nicl-nno commented on protollm/docs_processing/parsing/parsers/pdf/utilities.py
> +    #                 return pages_structure[1:]  # return document without title
Можно подчистить комментарии

2024-12-15 22:27 UTC, nicl-nno commented on protollm/rags/settings/es_settings.py
> +CONFIG_PATH = Path(dirname(dirname(__file__)) + '/stores/elasticsearch/configs')
Вроде можно весь путь через Path собрать, без '+'

2024-12-15 22:31 UTC, nicl-nno requested changes
Лучше поправить пару минорных комментариев, пока коду думаю пока можно так оставить.

2024-12-16 10:18 UTC, vanoha commented on protollm/docs_processing/parsing/parsers/utilities.py
> +TITLE_KEYWORDS = ['альметьевск', 'казань']
Этот модуль будет в другом PR.

2024-12-16 10:26 UTC, vanoha commented on protollm/docs_processing/parsing/parsers/pdf/utilities.py
> +    #                 return pages_structure[1:]  # return document without title
Этот модуль будет в другом PR.

2024-12-16 15:46 UTC, nicl-nno approved these changes

2024-12-17 09:05 UTC, merged